#!/bin/sh

HOSTNAME=`hostname`
MSG="$HOSTNAME Remaining battery level below threshold on UPS $1, initiating a shutdown."
FROM="nathanjanke96@gmail.com"
TO="root"
#
(
   echo "From: $FROM"
   echo "To: $TO"
   echo "$MSG"
   echo " "
   /usr/sbin/apcaccess status
) | sendmail -t -f root
exit 0
