#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the
# UPS goes back on to the mains after a power failure.
# An email notification is sent to the $SYSADMIN email address defined in /etc/apcupsd/apccontrol.
#

HOSTNAME=`hostname`
FROM="nathanjanke96@gmail.com"
TO="root"
MSG="$HOSTNAME UPS $1 Power has returned"
#
(
   echo "From: $FROM"
   echo "To: $TO"
   echo "Subject: UPS Off Battery"
   echo "$MSG"
   echo " "
   /usr/sbin/apcaccess status
) | sendmail -t -f root
exit 0
