#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the UPS
# goes on batteries.
# An email notification is sent to the $SYSADMIN email address defined in /etc/apcupsd/apccontrol.
#

HOSTNAME=`hostname`
MSG="$HOSTNAME UPS $1 Power Failure !!!"
FROM="nathanjanke96@gmail.com"
TO="root"
#
(
   echo "From: $FROM"
   echo "To: $TO"
   echo "Subject: UPS On Battery"
   echo "$MSG"
   echo " "
   /usr/sbin/apcaccess status
) | sendmail -t -f root
exit 0
